In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [2]:
df = pd.read_csv('ai4i2020.csv')

In [3]:
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0   
1                    1408         46.3                3                0    0   
2                    1498         49.4                5                0    0   
3                    1433         39.5                7                0    0   
4                    1408         40.0                9                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

In [4]:
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [5]:
df.dtypes

UDI                          int64
Product ID                  object
Type                        object
Air temperature [K]        float64
Process temperature [K]    float64
Rotational speed [rpm]       int64
Torque [Nm]                float64
Tool wear [min]              int64
Machine failure              int64
TWF                          int64
HDF                          int64
PWF                          int64
OSF                          int64
RNF                          int64
dtype: object

In [6]:
df['Type'].unique()

array(['M', 'L', 'H'], dtype=object)

In [7]:
types = pd.get_dummies(df['Type'], drop_first=True)

In [8]:
types

L  M
0     0  1
1     1  0
2     1  0
3     1  0
4     1  0
...  .. ..
9995  0  1
9996  0  0
9997  0  1
9998  0  0
9999  0  1

[10000 rows x 2 columns]

In [9]:
df = pd.concat([df, types], axis=1)

In [10]:
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0   
1                    1408         46.3                3                0    0   
2                    1498         49.4                5                0    0   
3                    1433         39.5                7                0    0   
4                    1408         40.0                9                0    0   

   HDF  PWF  OSF  RNF  L  M  
0    0    0    0    0  0  1  
1    0    0    0    0  1  0  
2    0    0    0    0  1  0  
3    0    0    0    0  1  0  
4    0    0    0    0  1  0

In [11]:
df.drop(columns=['Product ID','Type','UDI'],inplace=True)

In [12]:
df.head()

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                298.1                    308.6                    1551   
1                298.2                    308.7                    1408   
2                298.1                    308.5                    1498   
3                298.2                    308.6                    1433   
4                298.2                    308.7                    1408   

   Torque [Nm]  Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  L  \
0         42.8                0                0    0    0    0    0    0  0   
1         46.3                3                0    0    0    0    0    0  1   
2         49.4                5                0    0    0    0    0    0  1   
3         39.5                7                0    0    0    0    0    0  1   
4         40.0                9                0    0    0    0    0    0  1   

   M  
0  1  
1  0  
2  0  
3  0  
4  0

In [13]:
df.describe()

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
count         10000.000000             10000.000000            10000.000000   
mean            300.004930               310.005560             1538.776100   
std               2.000259                 1.483734              179.284096   
min             295.300000               305.700000             1168.000000   
25%             298.300000               308.800000             1423.000000   
50%             300.100000               310.100000             1503.000000   
75%             301.500000               311.100000             1612.000000   
max             304.500000               313.800000             2886.000000   

        Torque [Nm]  Tool wear [min]  Machine failure           TWF  \
count  10000.000000     10000.000000     10000.000000  10000.000000   
mean      39.986910       107.951000         0.033900      0.004600   
std        9.968934        63.654147         0.180981      0.067671   
min        3.800000         0.000000         0.000000      0.000000   
25%       33.200000        53.000000         0.000000      0.000000   
50%       40.100000       108.000000         0.000000      0.000000   
75%       46.800000       162.000000         0.000000      0.000000   
max       76.600000       253.000000         1.000000      1.000000   

                HDF           PWF           OSF          RNF             L  \
count  10000.000000  10000.000000  10000.000000  10000.00000  10000.000000   
mean       0.011500      0.009500      0.009800      0.00190      0.600000   
std        0.106625      0.097009      0.098514      0.04355      0.489922   
min        0.000000      0.000000      0.000000      0.00000      0.000000   
25%        0.000000      0.000000      0.000000      0.00000      0.000000   
50%        0.000000      0.000000      0.000000      0.00000      1.000000   
75%        0.000000      0.000000      0.000000      0.00000      1.000000   
max        1.000000      1.000000      1.000000      1.00000      1.000000   

                  M  
count  10000.000000  
mean       0.299700  
std        0.458149  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        1.000000  
max        1.000000

In [14]:
from pandas_profiling import ProfileReport

In [15]:
pf=ProfileReport(df)

In [16]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [17]:
X = df.iloc[:,1:]

In [18]:
X.head()

Process temperature [K]  Rotational speed [rpm]  Torque [Nm]  \
0                    308.6                    1551         42.8   
1                    308.7                    1408         46.3   
2                    308.5                    1498         49.4   
3                    308.6                    1433         39.5   
4                    308.7                    1408         40.0   

   Tool wear [min]  Machine failure  TWF  HDF  PWF  OSF  RNF  L  M  
0                0                0    0    0    0    0    0  0  1  
1                3                0    0    0    0    0    0  1  0  
2                5                0    0    0    0    0    0  1  0  
3                7                0    0    0    0    0    0  1  0  
4                9                0    0    0    0    0    0  1  0

In [19]:
y = df.iloc[:,0]

In [20]:
y.head()

0    298.1
1    298.2
2    298.1
3    298.2
4    298.2
Name: Air temperature [K], dtype: float64

In [21]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()

In [22]:
linear.fit(X,y)

LinearRegression()

In [23]:
linear.intercept_ 

-64.18761920950135

In [24]:
linear.coef_

array([ 1.17359962e+00,  1.90017941e-04,  2.61784525e-04,  8.44526443e-05,
       -9.21519921e-02,  2.05724576e-01,  1.78046694e+00,  1.41800466e-01,
       -3.99593243e-02, -5.10809701e-02,  4.04800429e-02,  4.91080260e-02])

In [25]:
linear.predict([[308.6,1551,42.8,0,0,0,0,0,0,0,0,1]])

C:\Users\argha\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([298.34025388])

In [30]:
file = 'Predictive_Maintenance_model.pkl'
pickle.dump(linear,open(file,'wb'))

In [31]:
saved_model = pickle.load(open(file,'rb'))

In [32]:
saved_model.predict([[308.6,1551,42.8,0,0,0,0,0,0,0,0,1]])

C:\Users\argha\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([298.34025388])

In [33]:
linear.score(X,y)

0.7757120716459627